version: '3.0'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    env_file: ./.env.prod
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: always
    env_file: ./.env.prod
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "${PORT}:${PORT}"